### ISSUE TITLE
Improve locking performance

### ISSUE THREAD

**Issue by veddan** [veddan/rust-concurrent-hashmap#4]
`RWLock`s can be slow, `Mutex` might be faster. Obviously might depend on read/write ratio. Needs benchmarks.
Last time I checked, lots of time was spent doing virtual calls to access thread-locals (is_panicking) on low-contention scenarios, see https://github.com/rust-lang/rust/issues/25088.

**Comment by arthurprs** [comment]
#5 addresses this.
