### ISSUE TITLE
Is there academic paper behind this type of Hash Table?

### ISSUE THREAD

**Issue by stereobooster** [veddan/rust-concurrent-hashmap#7]
Any formal description in Readme would be very helpful. Thanks

**Comment by veddan** [comment]
I added some info in the README and in rustdoc.

I can't point you to any academic papers on the top of my head, but I think the strategy of splitting the key space into partitions based on some bits from the hash is very common.
It's sometimes called "sharding". The general technique is often called "lock striping".

**Comment by stereobooster** [comment]
> strategy of splitting the key space into partitions based on some bits from the hash is very common. It's sometimes called "sharding"

Makes sense. Thank you. Found another implementation maybe you will be interested https://github.com/ndokmai/nonblockinghashmap
